### PR TITLE
update dependencies to suite Elixir 1.1.0

### PR DESCRIPTION
**Pull request by GalaxyGorilla**
Dependency updates for upcoming Elixir 1.1.0. I still have problem with conform despite the fixes from @0xAX mentioned in https://github.com/carosio/unimux/issues/9.

### CODE REVIEW

**Comment by GalaxyGorilla** [comment]
The travis tests are ok, also the test relevant for my local system. So I think this is ready to merge.

**Comment by GalaxyGorilla** [comment]
Changed dependency exrm from bitwalker/exrm to xerions/exrm.

**Comment by thz** [comment]
in mix.exs:

```
elixir: "~> 1.0",
```

causes:

```
| warning: the dependency :coverex requires Elixir "~> 1.0.0" but you are running on v1.1.0
```

We should probably allow 1.0 and 1.1 or go to 1.1 only.

**Comment by GalaxyGorilla** [comment]
updated to '~> 1.1'

**Pull request merged**
